import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Anton } from "next/font/google";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const anton = Anton({
  subsets: ["latin"],
  weight: "400",           // Anton only has 400
  variable: "--font-anton" // CSS variable name
});


const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Choose what you need
  variable: "--font-jetbrains"
});

export const metadata: Metadata = {
  title: "BiasBuster",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${anton.variable} ${jetbrains.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
