"""create users table

Revision ID: 0dc71500b3e4
Revises: 
Create Date: 2026-07-06 20:26:34.701430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dc71500b3e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_filename', sa.String(), nullable=False),
    sa.Column('model_filename', sa.String(), nullable=False),
    sa.Column('dataset_rows', sa.Integer(), nullable=True),
    sa.Column('dataset_columns', sa.Integer(), nullable=True),
    sa.Column('dataset_columns_list', sa.JSON(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=True),
    sa.Column('model_supports_predict_proba', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_records_id'), 'upload_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_records_id'), table_name='upload_records')
    op.drop_table('upload_records')
    # ### end Alembic commands ###
