"""add_auth_fields

Revision ID: 3132eab6d099
Revises: 
Create Date: 2026-07-06 17:25:54.704880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3132eab6d099'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bias_audit_records', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bias_audit_records_user_id'), 'bias_audit_records', ['user_id'], unique=False)
    op.create_foreign_key(None, 'bias_audit_records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('bias_mitigation_runs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bias_mitigation_runs_user_id'), 'bias_mitigation_runs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'bias_mitigation_runs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('correction_records', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_correction_records_user_id'), 'correction_records', ['user_id'], unique=False)
    op.create_foreign_key(None, 'correction_records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('experiment_runs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_experiment_runs_user_id'), 'experiment_runs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'experiment_runs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('fairness_experiment_reports', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_fairness_experiment_reports_user_id'), 'fairness_experiment_reports', ['user_id'], unique=False)
    op.create_foreign_key(None, 'fairness_experiment_reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('mitigation_rankings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_mitigation_rankings_user_id'), 'mitigation_rankings', ['user_id'], unique=False)
    op.create_foreign_key(None, 'mitigation_rankings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('optimization_runs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_optimization_runs_user_id'), 'optimization_runs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'optimization_runs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('refresh_tokens', sa.Column('user_agent', sa.String(length=500), nullable=True))
    op.add_column('refresh_tokens', sa.Column('ip_address', sa.String(length=100), nullable=True))
    op.add_column('refresh_tokens', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('upload_records', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_upload_records_user_id'), 'upload_records', ['user_id'], unique=False)
    op.create_foreign_key(None, 'upload_records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('auth_provider_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_password_change', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_password_change')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'auth_provider_id')
    op.drop_constraint(None, 'upload_records', type_='foreignkey')
    op.drop_index(op.f('ix_upload_records_user_id'), table_name='upload_records')
    op.drop_column('upload_records', 'user_id')
    op.drop_column('refresh_tokens', 'last_used_at')
    op.drop_column('refresh_tokens', 'ip_address')
    op.drop_column('refresh_tokens', 'user_agent')
    op.drop_constraint(None, 'optimization_runs', type_='foreignkey')
    op.drop_index(op.f('ix_optimization_runs_user_id'), table_name='optimization_runs')
    op.drop_column('optimization_runs', 'user_id')
    op.drop_constraint(None, 'mitigation_rankings', type_='foreignkey')
    op.drop_index(op.f('ix_mitigation_rankings_user_id'), table_name='mitigation_rankings')
    op.drop_column('mitigation_rankings', 'user_id')
    op.drop_constraint(None, 'fairness_experiment_reports', type_='foreignkey')
    op.drop_index(op.f('ix_fairness_experiment_reports_user_id'), table_name='fairness_experiment_reports')
    op.drop_column('fairness_experiment_reports', 'user_id')
    op.drop_constraint(None, 'experiment_runs', type_='foreignkey')
    op.drop_index(op.f('ix_experiment_runs_user_id'), table_name='experiment_runs')
    op.drop_column('experiment_runs', 'user_id')
    op.drop_constraint(None, 'correction_records', type_='foreignkey')
    op.drop_index(op.f('ix_correction_records_user_id'), table_name='correction_records')
    op.drop_column('correction_records', 'user_id')
    op.drop_constraint(None, 'bias_mitigation_runs', type_='foreignkey')
    op.drop_index(op.f('ix_bias_mitigation_runs_user_id'), table_name='bias_mitigation_runs')
    op.drop_column('bias_mitigation_runs', 'user_id')
    op.drop_constraint(None, 'bias_audit_records', type_='foreignkey')
    op.drop_index(op.f('ix_bias_audit_records_user_id'), table_name='bias_audit_records')
    op.drop_column('bias_audit_records', 'user_id')
    # ### end Alembic commands ###
