"""new schema

Revision ID: a030c94ed537
Revises: 
Create Date: 2026-07-08 23:13:57.766235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a030c94ed537'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.Enum('EMAIL', 'GOOGLE', 'GITHUB', name='authprovider'), nullable=False),
    sa.Column('auth_provider_id', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_password_change', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_table('correction_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correction_id', sa.String(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('target_column', sa.String(), nullable=False),
    sa.Column('sensitive_columns', sa.JSON(), nullable=False),
    sa.Column('dataset_export_path', sa.String(), nullable=True),
    sa.Column('model_export_path', sa.String(), nullable=True),
    sa.Column('report_export_path', sa.String(), nullable=True),
    sa.Column('metrics_before', sa.JSON(), nullable=False),
    sa.Column('metrics_after', sa.JSON(), nullable=False),
    sa.Column('improvements', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correction_records_correction_id'), 'correction_records', ['correction_id'], unique=True)
    op.create_index(op.f('ix_correction_records_id'), 'correction_records', ['id'], unique=False)
    op.create_index(op.f('ix_correction_records_user_id'), 'correction_records', ['user_id'], unique=False)
    op.create_table('model_registery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('parent_model_id', sa.String(), nullable=True),
    sa.Column('optimization_method', sa.String(), nullable=True),
    sa.Column('mitigation_strategy', sa.String(), nullable=True),
    sa.Column('retraining_method', sa.String(), nullable=True),
    sa.Column('artifact_path', sa.String(), nullable=False),
    sa.Column('artifact_size_bytes', sa.Integer(), nullable=True),
    sa.Column('performance_metrics', sa.JSON(), nullable=False),
    sa.Column('fairness_metrics', sa.JSON(), nullable=False),
    sa.Column('operational_metrics', sa.JSON(), nullable=True),
    sa.Column('combined_score', sa.Float(), nullable=False),
    sa.Column('recommended_for', sa.String(), nullable=True),
    sa.Column('recommendation_reason', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('experiment_id', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_registery_id'), 'model_registery', ['id'], unique=False)
    op.create_index(op.f('ix_model_registery_model_id'), 'model_registery', ['model_id'], unique=True)
    op.create_index(op.f('ix_model_registery_parent_model_id'), 'model_registery', ['parent_model_id'], unique=False)
    op.create_index(op.f('ix_model_registery_source_type'), 'model_registery', ['source_type'], unique=False)
    op.create_index(op.f('ix_model_registery_upload_id'), 'model_registery', ['upload_id'], unique=False)
    op.create_index(op.f('ix_model_registery_user_id'), 'model_registery', ['user_id'], unique=False)
    op.create_table('optimization_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('optimization_id', sa.String(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('target_column', sa.String(), nullable=False),
    sa.Column('sensitive_columns', sa.JSON(), nullable=False),
    sa.Column('optimization_method', sa.String(), nullable=False),
    sa.Column('best_params', sa.JSON(), nullable=False),
    sa.Column('metrics_before', sa.JSON(), nullable=False),
    sa.Column('metrics_after', sa.JSON(), nullable=False),
    sa.Column('improvements', sa.JSON(), nullable=False),
    sa.Column('artifact_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_runs_id'), 'optimization_runs', ['id'], unique=False)
    op.create_index(op.f('ix_optimization_runs_optimization_id'), 'optimization_runs', ['optimization_id'], unique=True)
    op.create_index(op.f('ix_optimization_runs_user_id'), 'optimization_runs', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_id'), 'refresh_tokens', ['token_id'], unique=True)
    op.create_table('upload_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_filename', sa.String(), nullable=False),
    sa.Column('original_dataset_filename', sa.String(), nullable=True),
    sa.Column('model_filename', sa.String(), nullable=False),
    sa.Column('original_model_filename', sa.String(), nullable=True),
    sa.Column('dataset_rows', sa.Integer(), nullable=True),
    sa.Column('dataset_columns', sa.Integer(), nullable=True),
    sa.Column('dataset_columns_list', sa.JSON(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=True),
    sa.Column('model_supports_predict_proba', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_records_id'), 'upload_records', ['id'], unique=False)
    op.create_index(op.f('ix_upload_records_user_id'), 'upload_records', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_index(op.f('ix_workspaces_user_id'), 'workspaces', ['user_id'], unique=False)
    op.create_table('bias_audit_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('audit_stage', sa.Integer(), nullable=True),
    sa.Column('audit_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bias_audit_records_user_id'), 'bias_audit_records', ['user_id'], unique=False)
    op.create_table('bias_mitigation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('sensitive_attribute', sa.String(), nullable=True),
    sa.Column('strategy_used', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('artifact_model_path', sa.String(), nullable=True),
    sa.Column('artifact_dataset_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bias_mitigation_runs_user_id'), 'bias_mitigation_runs', ['user_id'], unique=False)
    op.create_table('dashboard_experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_experiments_id'), 'dashboard_experiments', ['id'], unique=False)
    op.create_index(op.f('ix_dashboard_experiments_user_id'), 'dashboard_experiments', ['user_id'], unique=False)
    op.create_index(op.f('ix_dashboard_experiments_workspace_id'), 'dashboard_experiments', ['workspace_id'], unique=False)
    op.create_table('experiment_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('target_column', sa.String(), nullable=False),
    sa.Column('sensitive_columns', sa.JSON(), nullable=False),
    sa.Column('strategies_tested', sa.JSON(), nullable=False),
    sa.Column('metrics_before', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('best_strategy', sa.String(), nullable=True),
    sa.Column('combined_score', sa.Float(), nullable=True),
    sa.Column('insights', sa.String(), nullable=True),
    sa.Column('total_duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_runs_experiment_id'), 'experiment_runs', ['experiment_id'], unique=True)
    op.create_index(op.f('ix_experiment_runs_id'), 'experiment_runs', ['id'], unique=False)
    op.create_index(op.f('ix_experiment_runs_user_id'), 'experiment_runs', ['user_id'], unique=False)
    op.create_table('fairness_experiment_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('section_flags', sa.JSON(), nullable=False),
    sa.Column('report_payload', sa.JSON(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=False),
    sa.Column('json_path', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fairness_experiment_reports_experiment_id'), 'fairness_experiment_reports', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_fairness_experiment_reports_id'), 'fairness_experiment_reports', ['id'], unique=False)
    op.create_index(op.f('ix_fairness_experiment_reports_report_id'), 'fairness_experiment_reports', ['report_id'], unique=True)
    op.create_index(op.f('ix_fairness_experiment_reports_upload_id'), 'fairness_experiment_reports', ['upload_id'], unique=False)
    op.create_index(op.f('ix_fairness_experiment_reports_user_id'), 'fairness_experiment_reports', ['user_id'], unique=False)
    op.create_table('mitigation_rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('metrics_before', sa.JSON(), nullable=False),
    sa.Column('metrics_after', sa.JSON(), nullable=False),
    sa.Column('ranking_score', sa.Float(), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitigation_rankings_id'), 'mitigation_rankings', ['id'], unique=False)
    op.create_index(op.f('ix_mitigation_rankings_upload_id'), 'mitigation_rankings', ['upload_id'], unique=False)
    op.create_index(op.f('ix_mitigation_rankings_user_id'), 'mitigation_rankings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mitigation_rankings_user_id'), table_name='mitigation_rankings')
    op.drop_index(op.f('ix_mitigation_rankings_upload_id'), table_name='mitigation_rankings')
    op.drop_index(op.f('ix_mitigation_rankings_id'), table_name='mitigation_rankings')
    op.drop_table('mitigation_rankings')
    op.drop_index(op.f('ix_fairness_experiment_reports_user_id'), table_name='fairness_experiment_reports')
    op.drop_index(op.f('ix_fairness_experiment_reports_upload_id'), table_name='fairness_experiment_reports')
    op.drop_index(op.f('ix_fairness_experiment_reports_report_id'), table_name='fairness_experiment_reports')
    op.drop_index(op.f('ix_fairness_experiment_reports_id'), table_name='fairness_experiment_reports')
    op.drop_index(op.f('ix_fairness_experiment_reports_experiment_id'), table_name='fairness_experiment_reports')
    op.drop_table('fairness_experiment_reports')
    op.drop_index(op.f('ix_experiment_runs_user_id'), table_name='experiment_runs')
    op.drop_index(op.f('ix_experiment_runs_id'), table_name='experiment_runs')
    op.drop_index(op.f('ix_experiment_runs_experiment_id'), table_name='experiment_runs')
    op.drop_table('experiment_runs')
    op.drop_index(op.f('ix_dashboard_experiments_workspace_id'), table_name='dashboard_experiments')
    op.drop_index(op.f('ix_dashboard_experiments_user_id'), table_name='dashboard_experiments')
    op.drop_index(op.f('ix_dashboard_experiments_id'), table_name='dashboard_experiments')
    op.drop_table('dashboard_experiments')
    op.drop_index(op.f('ix_bias_mitigation_runs_user_id'), table_name='bias_mitigation_runs')
    op.drop_table('bias_mitigation_runs')
    op.drop_index(op.f('ix_bias_audit_records_user_id'), table_name='bias_audit_records')
    op.drop_table('bias_audit_records')
    op.drop_index(op.f('ix_workspaces_user_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_upload_records_user_id'), table_name='upload_records')
    op.drop_index(op.f('ix_upload_records_id'), table_name='upload_records')
    op.drop_table('upload_records')
    op.drop_index(op.f('ix_refresh_tokens_token_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_optimization_runs_user_id'), table_name='optimization_runs')
    op.drop_index(op.f('ix_optimization_runs_optimization_id'), table_name='optimization_runs')
    op.drop_index(op.f('ix_optimization_runs_id'), table_name='optimization_runs')
    op.drop_table('optimization_runs')
    op.drop_index(op.f('ix_model_registery_user_id'), table_name='model_registery')
    op.drop_index(op.f('ix_model_registery_upload_id'), table_name='model_registery')
    op.drop_index(op.f('ix_model_registery_source_type'), table_name='model_registery')
    op.drop_index(op.f('ix_model_registery_parent_model_id'), table_name='model_registery')
    op.drop_index(op.f('ix_model_registery_model_id'), table_name='model_registery')
    op.drop_index(op.f('ix_model_registery_id'), table_name='model_registery')
    op.drop_table('model_registery')
    op.drop_index(op.f('ix_correction_records_user_id'), table_name='correction_records')
    op.drop_index(op.f('ix_correction_records_id'), table_name='correction_records')
    op.drop_index(op.f('ix_correction_records_correction_id'), table_name='correction_records')
    op.drop_table('correction_records')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
