"""add email

Revision ID: f061f6c4b092
Revises: 0dc71500b3e4
Create Date: 2026-07-06 21:07:19.033687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f061f6c4b092'
down_revision: Union[str, Sequence[str], None] = '0dc71500b3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mitigation_reports_id'), table_name='mitigation_reports')
    op.drop_table('mitigation_reports')
    op.drop_table('bias_mitigation_runs')
    op.drop_table('bias_audit_records')
    op.drop_index(op.f('ix_bias_reports_id'), table_name='bias_reports')
    op.drop_table('bias_reports')
    op.add_column('upload_records', sa.Column('original_dataset_filename', sa.String(), nullable=True))
    op.add_column('upload_records', sa.Column('original_model_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_records', 'original_model_filename')
    op.drop_column('upload_records', 'original_dataset_filename')
    op.create_table('bias_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bias_present', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('bias_driver', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bias_severity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dataset_health', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('target_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sensitive_attributes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sensitive_audit', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('warnings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_records.id'], name=op.f('bias_reports_upload_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bias_reports_pkey'))
    )
    op.create_index(op.f('ix_bias_reports_id'), 'bias_reports', ['id'], unique=False)
    op.create_table('bias_audit_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('audit_stage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('audit_result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_records.id'], name=op.f('bias_audit_records_upload_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bias_audit_records_pkey'))
    )
    op.create_table('bias_mitigation_runs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sensitive_attribute', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('strategy_used', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('artifact_model_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('artifact_dataset_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_records.id'], name=op.f('bias_mitigation_runs_upload_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bias_mitigation_runs_pkey'))
    )
    op.create_table('mitigation_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bias_report_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('method_used', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rows_before', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rows_after', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('before_metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('after_metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('improvement_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bias_report_id'], ['bias_reports.id'], name=op.f('mitigation_reports_bias_report_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mitigation_reports_pkey'))
    )
    op.create_index(op.f('ix_mitigation_reports_id'), 'mitigation_reports', ['id'], unique=False)
    # ### end Alembic commands ###
